[project]
name = "bloggy"
version = "0.0.1"
description = "A basic flask-based blog app."
dependencies = [
    "flask", "bleach", "markdown", "aws-wsgi", "cattrs", "WTForms"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
